"""Six synthetic judges, five implanted defects, one report.

Every judge here is simulated with a known defect dial, so the demo doubles as
an end-to-end validation: the audit must flag exactly the implanted defect and
nothing on the clean judge.  All seeds are fixed; the report is regenerated by
CI and diffed against the committed copy.
"""

from __future__ import annotations

from pathlib import Path

from judgekit.audit import AuditReport, run_audit
from judgekit.report import (
    inject,
    position_figure,
    probe_by_name,
    reliability_figure,
    render_markdown,
    score_distribution_figure,
)
from judgekit.schema import Verdict
from judgekit.synthetic import (
    binary_judge,
    binary_world,
    graded_items,
    graded_judge,
    human_graded,
    human_pairwise,
    pair_items,
    pairwise_judge,
)

# What each demo judge does wrong, in the words the summary table shows.
IMPLANTS: dict[str, str] = {
    "clean": "nothing",
    "first-picker": "takes the presented-first candidate 35% of the time",
    "length-lover": "adds standardized length to perceived quality",
    "self-server": "adds one scale point when the candidate is its own model",
    "middler": "halves every departure from the scale midpoint",
    "overconfident": "sharpens every claimed probability on the logit scale",
}

SUMMARY_COLUMNS = [
    ("quadratic-weighted kappa", "kappa_qw"),
    ("position preference", "position"),
    ("verbosity bias", "verbosity"),
    ("self-preference", "self-pref"),
    ("central tendency", "spread"),
    ("expected calibration error", "ECE"),
]


def build_audits() -> list[AuditReport]:
    graded = graded_items(300, seed=0)
    human_g = human_graded(graded)
    pairs = pair_items(200, seed=0, n_identical=20)
    human_p = human_pairwise(pairs)
    probabilities, outcomes = binary_world(1000, seed=0)
    human: list[Verdict] = [*human_g, *human_p, *outcomes]

    judges: list[list[Verdict]] = [
        [
            *graded_judge(graded, judge_id="clean", seed=1, n_samples=3),
            *pairwise_judge(pairs, judge_id="clean", seed=2, n_samples=2),
            *binary_judge(probabilities, judge_id="clean"),
        ],
        list(pairwise_judge(pairs, judge_id="first-picker", seed=3, position=0.35, n_samples=2)),
        [
            *graded_judge(graded, judge_id="length-lover", seed=4, verbosity=0.9),
            *pairwise_judge(pairs, judge_id="length-lover", seed=5, verbosity=0.5),
        ],
        list(graded_judge(graded, judge_id="self-server", seed=6, self_preference=1.0)),
        list(graded_judge(graded, judge_id="middler", seed=7, shrink=0.5)),
        list(binary_judge(probabilities, judge_id="overconfident", temperature=0.5)),
    ]
    return [run_audit(verdicts, human, judge_model="judge-model") for verdicts in judges]


def summary_table(audits: list[AuditReport]) -> str:
    header = "| judge | implanted defect | " + " | ".join(label for _, label in SUMMARY_COLUMNS)
    lines = [
        header + " | flags |",
        "|---|---|" + "---|" * (len(SUMMARY_COLUMNS) + 1),
    ]
    for audit in audits:
        cells = []
        for probe_name, _ in SUMMARY_COLUMNS:
            probe = probe_by_name(audit, probe_name)
            if probe is None:
                cells.append("-")
            elif probe.triggered is True:
                cells.append(f"**{probe.value:.2f}**")
            else:
                cells.append(f"{probe.value:.2f}")
        flagged = ", ".join(flag.name for flag in audit.flags) or "none"
        implant = IMPLANTS.get(audit.judge_id, "?")
        lines.append(
            f"| {audit.judge_id} | {implant} | " + " | ".join(cells) + f" | {flagged} |"
        )
    return "\n".join(lines)


def write_demo(out_dir: Path) -> list[AuditReport]:
    out_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = out_dir / "figures"
    figures_dir.mkdir(exist_ok=True)

    audits = build_audits()
    table = summary_table(audits)

    preamble = (
        "Every judge is synthetic with a known implanted defect, so this report is "
        "also a test: bold flagged values must sit exactly where defects were implanted, "
        "and the clean judge's row must carry none.\n\n" + table + "\n\n"
        "![position preference](figures/position.png)\n"
        "![reliability](figures/reliability.png)\n"
        "![score spread](figures/middler_scores.png)"
    )
    report = render_markdown(audits, "judgekit demo report", preamble=preamble)
    (out_dir / "report.md").write_text(report, encoding="utf-8")
    (out_dir / "summary.md").write_text(table + "\n", encoding="utf-8")

    position_figure(audits, figures_dir / "position.png")
    reliability_figure(audits, figures_dir / "reliability.png")
    for audit in audits:
        if audit.judge_id == "middler":
            score_distribution_figure(audit, figures_dir / "middler_scores.png")
    return audits


def inject_readme(readme_path: Path, results_dir: Path) -> None:
    summary = (results_dir / "summary.md").read_text(encoding="utf-8")
    text = readme_path.read_text(encoding="utf-8")
    readme_path.write_text(inject(text, "demo", summary), encoding="utf-8")
